version: '3.8'

services:
  gateway:
    container_name: api_gateway
    image: nguyenduc1603/book-brain-gateway:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT:-4000}:8080"
    depends_on:
      - book_brain
      - recommend
    restart: unless-stopped
    networks:
      - app-network

  book_brain:
    container_name: book_brain_app
    image: nguyenduc1603/book_brain:latest
    pull_policy: always
    env_file:
      - .env
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - app-network

  recommend:
    container_name: recommend_service
    image: nguyenduc1603/book-brain-ai-service:latest
    pull_policy: always
    env_file:
      - .env
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
