version: '3'
services:
  web:
    image: nguyenduc1603/book-brain-ai-service:latest
    pull_policy: always
#    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py