version: '3.8'

services:
  app:
    container_name: book_brain_app
    image: nguyenduc1603/book_brain:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

    # Nếu cần test local build thì mở 2 dòng dưới và comment image phía trên
    # build:
    #   context: .

# Database chạy ngoài nên compose này không khởi tạo service database
